Add formula highlighting in Cell Editor
dmaevsky/ellx-app pull request #11
Opened 2022-01-17 08:05 UTC by ax2mx

- Handle correct caret position on formula modification
- Add «black-box» tokenizer function
- Add unparsed state, input & paste handling
- Move autoSizeEditor() into CellEditor.svelte
- Change editor click logic
- Fix toggle comment support

2022-01-17 10:51 UTC, dmaevsky commented
![](https://github.trello.services/images/mini-trello-icon.png) [asdadsfg](https://trello.com/c/PgmvmI9Z/45-asdadsfg)

2022-01-28 13:13 UTC, dmaevsky requested changes

2022-01-28 13:13 UTC, dmaevsky commented on src/sandbox/components/CellEditor.svelte
> +      console.log("Formula parsing error: ", e);
console.debug ? or remove

2022-01-28 13:13 UTC, dmaevsky commented on src/sandbox/components/CellEditor.svelte
> +  const parser = new ProgressiveEval(environment, () => {});
better initialize it directly in getTokens

2022-01-28 13:13 UTC, dmaevsky commented on src/sandbox/components/CellEditor.svelte
> +    let result = `<span id="highlight" class="highlighted_string">`
"#highlight" is too common as id, may have an id like this in the app itself

2022-01-28 13:13 UTC, dmaevsky commented on src/sandbox/components/CellEditor.svelte
> +    }
I believe you, but this is SO NOT CLEAR. Need comments

2022-01-28 13:13 UTC, dmaevsky commented on src/sandbox/components/CellEditor.svelte
> +    document.execCommand("insertHTML", false, text);
https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand
Deprecated: This feature is no longer recommended. 
No other option here?

2022-01-28 13:13 UTC, dmaevsky commented on src/sandbox/components/Grid.svelte
> +
I just saw the same code in CellEditor.svelte ?

2022-01-28 13:16 UTC, dmaevsky commented on src/sandbox/components/NodeNavigator.svelte
>    }
This is a standard TW class, normally not needed ?

2022-01-28 13:22 UTC, ax2mx commented on src/sandbox/components/CellEditor.svelte
> +      console.log("Formula parsing error: ", e);
I think it might be better to leave this notification at debug level.
Fixed.

2022-01-28 13:22 UTC, dmaevsky commented on src/utils/ui.js
> +export function togglePanel(selector) {
may be just name it "toggle"?

2022-01-28 15:55 UTC, ax2mx commented on src/sandbox/components/CellEditor.svelte
> +  const parser = new ProgressiveEval(environment, () => {});
Fixed.

2022-01-29 09:57 UTC, dmaevsky commented on src/sandbox/components/CellEditor.svelte
> +  import { getCaretPosition } from "../../utils/highlight";
extension .js 
It works with our bundler, but maybe not forever. At least this is the convention for now: we don't rely on node resolution algorithm whenever possible

2022-01-29 11:16 UTC, dmaevsky commented on src/sandbox/components/Grid.svelte
> +  $: if (selection && !document.querySelector("#ellx-node-navigator").classList.contains("hidden")) closeEditor();
better to make NodeNavigator hidden flag part of the store. Let's discuss: this is a very good example when state management becomes necessary

2022-02-02 10:50 UTC, merged